### ISSUE TITLE
Why isn't there an Attribute Data Table in layers?

### ISSUE THREAD

**Issue by moseleyi** [OpenICGC/QgisPlugin#11]
I loaded few layers in order to visualise elevation data like this:
![image](https://user-images.githubusercontent.com/16131590/208509291-ad9cbaee-e94a-44f2-91c3-8c92c319b7f1.png)
But there's no way to use DTM information in labelling the elevation?

**Comment by jarnaldich** [comment]
Elevation data is published as a Raster, so there is no direct way to use it for labelling (or at least not the way I figure you would like it). The alternative is to derive contour line via geoprocessing or use the already existing countour lines you can download from the "Topographic Referential" product: 
![image](https://user-images.githubusercontent.com/891959/208612211-52c893f4-b544-40cc-aa42-8c11e933f1ad.png)

The layer you are looking for is "relleu_l" in the download: 
![image](https://user-images.githubusercontent.com/891959/208612646-4e6676a2-9c47-4af9-a77e-5fdd0dfba173.png)

Also, I am closing the issue because we use GitHub just for software related bugs. Please use: https://icgc.cat/L-ICGC/Contacte/Bustia-de-contacte for data related questions.
